language: cpp
dist: xenial

# Minimal set of packages needed to compile EPICS Base
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - gcc-9
    - g++-9

compiler:
  - clang
  - gcc
  - gcc-9

env:
  - BRBASE=3.15 STATIC=NO
  - BRBASE=3.15 STATIC=YES
  - BRBASE=7.0  STATIC=NO
  - BRBASE=7.0  STATIC=YES

install:
  - ./.ci/travis-prepare.sh

script:
  - sed -i '/EPICS_BASE=/d' ./configure/RELEASE
  - echo -e "\nEPICS_BASE=$HOME/.source/epics-base" >> ./configure/RELEASE
  - cat ./configure/RELEASE
  - ./.ci/travis-build.sh
