dist: xenial
language: cpp
compiler:
  - gcc
  - clang

env:
 - BASE_BRANCH=7.0 STATIC=shared
 - BASE_BRANCH=7.0 STATIC=static
 - BASE_BRANCH=3.15 STATIC=shared
 - BASE_BRANCH=3.15 STATIC=static

install: ./.ci/install-epics.sh

script: make -j
