Document: regex-asub
Title: Debian regex-asub Manual
Author: <insert document author here>
Abstract: This manual describes what regex-asub is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/regex-asub/regex-asub.sgml.gz

Format: postscript
Files: /usr/share/doc/regex-asub/regex-asub.ps.gz

Format: text
Files: /usr/share/doc/regex-asub/regex-asub.text.gz

Format: HTML
Index: /usr/share/doc/regex-asub/html/index.html
Files: /usr/share/doc/regex-asub/html/*.html
